name: CloudFlare-Warp-Gui
summary: A GUI application for Cloudflare Warp on Linux
description: |
  A GUI application for Cloudflare WARP on Linux built with python using tkinter, and os.
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [amd64]

apps:
  Cloudflare-Warp-CLI-GUI:
    command: bin/Cloudflare-Warp-CLI-GUI
    plugs: [home, network, network-bind]

parts:
  Cloudflare-Warp-CLI-GUI:
    plugin: python
    source: https://github.com/airplaneboy14mc/Cloudflare-Warp-CLI-GUI.git
    
