name: cloudflare-warp-gui
summary: A gui for cloudflare warp for linux
description: |
  A gui for cloudflare warp using python, tkinter, and os for controling warp
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [amd64]

apps:
  cloudflare-warp-cli-gui:
    command: bin/cloudflare-warp-cli-gui
    plugs: [home, network, network-bind]

parts:
  cloudflare-warp-cli-gui:
    plugin: python
    source: https://github.com/airplaneboy14mc/Cloudflare-Warp-CLI-GUI.git
    