name: warpcli-connect-x64
version: '1.0'
summary: Cloudflare Warp CLI Connection
description: |
  A simple GUI application to connect/disconnect Cloudflare Warp CLI and install the package on Linux x64.
grade: devel
confinement: strict
base: core20

parts:
  warpcli-connect-x64:
    plugin: python
    source: .
    requirements:
      - tkinter
    stage-packages:
      - cloudflare-warp

apps:
  warpcli-connect-x64:
    command: python3 $SNAP/warpcli-connect-x64.py