name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev python3-wheel dh-python

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Build package
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        PACKAGE_NAME="cloudflare-warp-cli-gui_${VERSION}_all"
        python3 setup.py bdist_wheel
        mkdir "$PACKAGE_NAME"
        cp dist/*.whl "$PACKAGE_NAME"
        dpkg-deb --build "$PACKAGE_NAME"
        mv "$PACKAGE_NAME".deb "cloudflare-warp-cli-gui_${VERSION}_all.deb"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-warp-cli-gui.deb
        path: cloudflare-warp-cli-gui_*.deb
