name: Build and Package

on:
  push:
    branches:
      - amd64-stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev python3-wheel dh-python

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: pip install wheel

    - name: Get latest tag
      id: get_latest_tag
      run: echo ::set-output name=latest_tag::$(git describe --tags --abbrev=0)

    - name: Increment tag
      id: increment_tag
      run: echo ::set-output name=tag::$(echo "${{ steps.get_latest_tag.outputs.latest_tag }}" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)

    - name: Build package
      run: |
        VERSION=${{ steps.increment_tag.outputs.tag }}
        PACKAGE_NAME="cloudflare-warp-cli-gui"
        python3 setup.py bdist_wheel
        rm -rf "$PACKAGE_NAME"
        mkdir "$PACKAGE_NAME"
        cp dist/*.whl "$PACKAGE_NAME"
        dpkg-deb --build "$PACKAGE_NAME"
        mv "$PACKAGE_NAME".deb "cloudflare-warp-cli-gui_${VERSION}_all.deb"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloudflare-warp-cli-gui.deb
        path: cloudflare-warp-cli-gui_*.deb
